project 'projectTDD.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projectTDD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectTDD

  target 'projectTDDTests' do
    inherit! :search_paths
    
    # Pods for testing
    pod "Quick"
    pod "Nimble"
  end

  target 'projectTDDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
